name: dockerfile

on:
  push:
    branches:
      - master
    paths:
      - '**/Dockerfile'
      - './github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@master
    - name: build node:latest
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        imageName:  ${{secrets.DOCKER_USERNAME}}/node
        platform: linux/amd64,linux/arm64,linux/arm/v7 # 你准备构建的镜像平台
        tag: latest
        dockerFile: ./node/latest/Dockerfile
        dockerHubUser: ${{ secrets.DOCKER_USERNAME }} # docker hub userid
        dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }} # docker hub password
    - name: build node:slim
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        imageName:  ${{secrets.DOCKER_USERNAME}}/node
        platform: linux/amd64,linux/arm64,linux/arm/v7 # 你准备构建的镜像平台
        tag: slim 
        dockerFile: ./node/slim/Dockerfile
        dockerHubUser: ${{ secrets.DOCKER_USERNAME }} # docker hub userid
        dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }} # docker hub password