name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.5
    -
      name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    -
      name: Build node:latest
      run: |
        docker buildx build \
          --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
          --output "type=image,push=false" \
          --tag banknight/node:latest \
          --file ./node/latest/Dockerfile ./node/latest
    -
      name: Build node:slim
      run: |
        docker buildx build \
          --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
          --output "type=image,push=false" \
          --tag banknight/node:slim \
          --file ./node/slim/Dockerfile ./node/slim
    -
      name: Show Images
      run: docker images           

