name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -
      name: Build node:latest
      uses: ilteoood/docker_buildx@master
      with: 
        publish: true
        imageName: banknight/node
        tag: latest
        dockerFile: ./node/latest/Dockerfile
        dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
        dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}