name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -
      name: Build node:latest
      uses: zmingxie/docker_buildx@master
      with:
          publish: true
          imageName: banknight/node
          tag: latest
          dockerFile: ./node/latest/Dockerfile
          dockerHubUser: ${{secrets.DOCKER_USERNAME}}
          dockerHubPassword: ${{secrets.DOCKER_PASSWORD}}
    -
      name: Build node:slim
      uses: zmingxie/docker_buildx@master
      with:
          publish: true
          imageName: banknight/node
          tag: slim
          dockerFile: ./node/slim/Dockerfile
          dockerHubUser: ${{secrets.DOCKER_USERNAME}}
          dockerHubPassword: ${{secrets.DOCKER_PASSWORD}}    
   

