name: sh

on:
  push:
    branches:
      - master
    paths:
      - '**/*.sh'
      - '**/sh.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2     
    -
      name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    -
      name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: 
        echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME}  --password-stdin 
        
    - name: Build 
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --tag ${DOCKER_USERNAME}/ipec-vpn-server \
            --push \
            github.com/hwdsl2/docker-ipsec-vpn-server.git
