name: sh

on:
  push:
    branches:
      - master
    paths:
      - '**/*.sh'
      - '**/sh.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2     
    -
      name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    -
      name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Build vpn
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: 
        echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME}  --password-stdin && \
        ./ipec-vpn-server/latest/build.sh
